language: cpp
sudo: required
dist: trusty
addons:
    apt:
        sources:
          # add PPAs with more up-to-date toolchains
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
        packages:
          # install toolchains
          - gcc-5
          - g++-5
          - clang-3.6
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7
script:
  - mkdir build
  - cd build
  - CXX="g++-4.8" CC="gcc-4.8" cmake BUILD_SUPERBUILD:BOOL=ON, BUILD_Boost:BOOL=ON, BUILD_Eigen:BOOL=ON and BUILD_OpenCV:BOOL=ON ..
  - make
  - ctest .
